### ISSUE TITLE
Add standard interface for drivetrain

### ISSUE THREAD

**Issue by AritroSaha10** [jfssvex/challenge-2022-a#1]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add a standard interface for the drivetrain, so that it can be reused in both autonomous and operator control code.

**Describe the technicals that might be involved in implementing this**
We would likely need to have two classes: `Drivetrain` and `SkidSteerDrive`. The former would be a virtual class, and the second would be the derived class. 

The `Drivetrain` class would include all of the functions needed for a drivetrain, for example, going forward, backwards, turning, stopping, as well as using tank and arcade control schemes. However, they would all be virtual as implementation would vary depending on what type of drivetrain is being used.

The `SkidSteerDrive` class would simply implement all of these functions using motor calls.

By using the `Drivetrain` class, we can easily swap out the base drivetrain control in case of an unexpected switch.

An alternative would to just create a `SkidSteerDrive` class with all of the functions previously mentioned. Either works, though the former is more flexible.

**Additional context**
None.

**Comment by hariskhawja** [comment]
I'll try and implement this.
