### ISSUE TITLE
Add puncher system manager

### ISSUE THREAD

**Issue by AritroSaha10** [jfssvex/challenge-2022-a#11]
**Describe the solution you'd like**
Create a puncher system manager that will manage all of its basic functionality and state management (wind up stage, ball loaded, ready to punch, etc.).

**Describe the technicals that might be involved in implementing this**
Implementation of the to-be added system manager base class (#10) with the basic functionality and state management mentioned previously.

**Additional context**
While a lot of power is required, it should be worth considering using the velocity commands, as it is important for the puncher to shoot consistently instead of just at the highest power it can. A manual PID controller should also be considered, but may be more complex with little benefit.

**Comment by AritroSaha10** [comment]
@hariskhawja @PraneethS42 did any of you want to work on this?

**Comment by hariskhawja** [comment]
okay I'll try and attempt this
Is the declaration about the same as SkidSteerDrive?

**Comment by AritroSaha10** [comment]
It should derive from the base System manager class. It doesn't need to be
extremely complicated, just a starting point that we can expand once we
have more specific information about the puncher.
