### ISSUE TITLE
Implement drivetrain op control

### ISSUE THREAD

**Issue by AritroSaha10** [jfssvex/challenge-2022-a#13]
**Describe the solution you'd like**
Now that we're almost done the drivetrain, we can finally get started on adding this. Simply add the ability to control the drivetrain using the controller during the operator control period.

**Describe the technicals that might be involved in implementing this**
Fetching data from controllers and passing them to either `tank` or `arcade` of the drivetrain object (both can be added with one of the commented out for easy swapping).

**Additional context**
Nope.

**Comment by AritroSaha10** [comment]
Either of you want to work on this? This should be pretty simple. @hariskhawja @PraneethS42

**Comment by PraneethS42** [comment]
I'll work on this one then.

**Comment by AritroSaha10** [comment]
@PraneethS42 Hey! Any progress?

**Comment by PraneethS42** [comment]
I'm about half done, should be completed tomorrow. Had a lot to do with AP
exams and school projects

**Comment by hariskhawja** [comment]
Aritro, if you don't mind, I'll try and debug the op control and push the commits.

**Comment by AritroSaha10** [comment]
@hariskhawja Did you already do so? If not, I can push the fixes (just saw your comments)

**Comment by AritroSaha10** [comment]
Finished in a00063223566331ee502b8c999a6d9eafcf5a4ee

**Comment by hariskhawja** [comment]
No, it's all good don't worry
