### ISSUE TITLE
Add globals 

### ISSUE THREAD

**Issue by AritroSaha10** [jfssvex/challenge-2022-a#2]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add a globals header and source folder for later use.

**Describe the technicals that might be involved in implementing this**
N/A

**Additional context**
None.

**Comment by PraneethS42** [comment]
Yep, I'll try and have it done by tomorrow.

**Comment by AritroSaha10** [comment]
Sounds good, just make sure to add your changes in a new branch and open a pull request once you're done.

**Comment by AritroSaha10** [comment]
Closed in #4
